spring.application.name=aes-crypto-webflux-service
server.port=8081

crypto.aes.nonce-length-bytes=12
crypto.aes.tag-length-bits=128
crypto.scheduler.thread-cap=0
crypto.scheduler.queue-capacity=1000

logging.level.net.celloscope.aes=INFO
